gAbilityDescription_None: @ 81F99CC
	.string "No special ability.$"

gAbilityDescription_Stench: @ 81F99E0
	.string "Helps repel wild POKéMON.$"

gAbilityDescription_Drizzle: @ 81F99FA
	.string "Summons rain in battle.$"

gAbilityDescription_SpeedBoost: @ 81F9A12
	.string "Gradually boosts SPEED.$"

gAbilityDescription_BattleArmor: @ 81F9A2A
	.string "Blocks critical hits.$"

gAbilityDescription_Sturdy: @ 81F9A40
	.string "Negates 1-hit KO attacks.$"

gAbilityDescription_Damp: @ 81F9A5A
	.string "Prevents self-destruction.$"

gAbilityDescription_Limber: @ 81F9A75
	.string "Prevents paralysis.$"

gAbilityDescription_SandVeil: @ 81F9A89
	.string "Ups evasion in a sandstorm.$"

gAbilityDescription_Static: @ 81F9AA5
	.string "Paralyzes on contact.$"

gAbilityDescription_VoltAbsorb: @ 81F9ABB
	.string "Turns electricity into HP.$"

gAbilityDescription_WaterAbsorb: @ 81F9AD6
	.string "Changes water into HP.$"

gAbilityDescription_Oblivious: @ 81F9AED
	.string "Prevents attraction.$"

gAbilityDescription_CloudNine: @ 81F9B02
	.string "Negates weather effects.$"

gAbilityDescription_CompoundEyes: @ 81F9B1B
	.string "Raises accuracy.$"

gAbilityDescription_Insomnia: @ 81F9B2C
	.string "Prevents sleep.$"

gAbilityDescription_ColorChange: @ 81F9B3C
	.string "Changes type to foe's move.$"

gAbilityDescription_Immunity: @ 81F9B58
	.string "Prevents poisoning.$"

gAbilityDescription_FlashFire: @ 81F9B6C
	.string "Powers up if hit by fire.$"

gAbilityDescription_ShieldDust: @ 81F9B86
	.string "Prevents added effects.$"

gAbilityDescription_OwnTempo: @ 81F9B9E
	.string "Prevents confusion.$"

gAbilityDescription_SuctionCups: @ 81F9BB2
	.string "Firmly anchors the body.$"

gAbilityDescription_Intimidate: @ 81F9BCB
	.string "Lowers the foe's ATTACK.$"

gAbilityDescription_ShadowTag: @ 81F9BE4
	.string "Prevents the foe's escape.$"

gAbilityDescription_RoughSkin: @ 81F9BFF
	.string "Hurts to touch.$"

gAbilityDescription_WonderGuard: @ 81F9C0F
	.string "“Super effective” hits.$"

gAbilityDescription_Levitate: @ 81F9C27
	.string "Not hit by GROUND attacks.$"

gAbilityDescription_EffectSpore: @ 81F9C42
	.string "Leaves spores on contact.$"

gAbilityDescription_Synchronize: @ 81F9C5C
	.string "Passes on status problems.$"

gAbilityDescription_ClearBody: @ 81F9C77
	.string "Prevents ability reduction.$"

gAbilityDescription_NaturalCure: @ 81F9C93
	.string "Heals upon switching out.$"

gAbilityDescription_LightningRod: @ 81F9CAD
	.string "Draws electrical moves.$"

gAbilityDescription_SereneGrace: @ 81F9CC5
	.string "Promotes added effects.$"

gAbilityDescription_SwiftSwim: @ 81F9CDD
	.string "Raises SPEED in rain.$"

gAbilityDescription_Chlorophyll: @ 81F9CF3
	.string "Raises SPEED in sunshine.$"

gAbilityDescription_Illuminate: @ 81F9D0D
	.string "Encounter rate increases.$"

gAbilityDescription_Trace: @ 81F9D27
	.string "Copies special ability.$"

gAbilityDescription_HugePower: @ 81F9D3F
	.string "Raises ATTACK.$"

gAbilityDescription_PoisonPoint: @ 81F9D4E
	.string "Poisons foe on contact.$"

gAbilityDescription_InnerFocus: @ 81F9D66
	.string "Prevents flinching.$"

gAbilityDescription_MagmaArmor: @ 81F9D7A
	.string "Prevents freezing.$"

gAbilityDescription_WaterVeil: @ 81F9D8D
	.string "Prevents burns.$"

gAbilityDescription_MagnetPull: @ 81F9D9D
	.string "Traps STEEL-type POKéMON.$"

gAbilityDescription_Soundproof: @ 81F9DB7
	.string "Avoids sound-based moves.$"

gAbilityDescription_RainDish: @ 81F9DD1
	.string "Slight HP recovery in rain.$"

gAbilityDescription_SandStream: @ 81F9DED
	.string "Summons a sandstorm.$"

gAbilityDescription_Pressure: @ 81F9E02
	.string "Raises foe's PP usage.$"

gAbilityDescription_ThickFat: @ 81F9E19
	.string "Heat-and-cold protection.$"

gAbilityDescription_EarlyBird: @ 81F9E33
	.string "Awakens quickly from sleep.$"

gAbilityDescription_FlameBody: @ 81F9E4F
	.string "Burns the foe on contact.$"

gAbilityDescription_RunAway: @ 81F9E69
	.string "Makes escaping easier.$"

gAbilityDescription_KeenEye: @ 81F9E80
	.string "Prevents loss of accuracy.$"

gAbilityDescription_HyperCutter: @ 81F9E9B
	.string "Prevents ATTACK reduction.$"

gAbilityDescription_Pickup: @ 81F9EB6
	.string "May pick up items.$"

gAbilityDescription_Truant: @ 81F9EC9
	.string "Moves only every two turns.$"

gAbilityDescription_Hustle: @ 81F9EE5
	.string "Trades accuracy for power.$"

gAbilityDescription_CuteCharm: @ 81F9F00
	.string "Infatuates on contact.$"

gAbilityDescription_Plus: @ 81F9F17
	.string "Powers up with MINUS.$"

gAbilityDescription_Minus: @ 81F9F2D
	.string "Powers up with PLUS.$"

gAbilityDescription_Forecast: @ 81F9F42
	.string "Changes with the weather.$"

gAbilityDescription_StickyHold: @ 81F9F5C
	.string "Prevents item theft.$"

gAbilityDescription_ShedSkin: @ 81F9F71
	.string "Heals the body by shedding.$"

gAbilityDescription_Guts: @ 81F9F8D
	.string "Ups ATTACK if suffering.$"

gAbilityDescription_MarvelScale: @ 81F9FA6
	.string "Ups DEFENSE if suffering.$"

gAbilityDescription_LiquidOoze: @ 81F9FC0
	.string "Draining causes injury.$"

gAbilityDescription_Overgrow: @ 81F9FD8
	.string "Ups GRASS moves in a pinch.$"

gAbilityDescription_Blaze: @ 81F9FF4
	.string "Ups FIRE moves in a pinch.$"

gAbilityDescription_Torrent: @ 81FA00F
	.string "Ups WATER moves in a pinch.$"

gAbilityDescription_Swarm: @ 81FA02B
	.string "Ups BUG moves in a pinch.$"

gAbilityDescription_RockHead: @ 81FA045
	.string "Prevents recoil damage.$"

gAbilityDescription_Drought: @ 81FA05D
	.string "Summons sunlight in battle.$"

gAbilityDescription_ArenaTrap: @ 81FA079
	.string "Prevents fleeing.$"

gAbilityDescription_VitalSpirit: @ 81FA08B
	.string "Prevents sleep.$"

gAbilityDescription_WhiteSmoke: @ 81FA09B
	.string "Prevents ability reduction.$"

gAbilityDescription_PurePower: @ 81FA0B7
	.string "Raises ATTACK.$"

gAbilityDescription_ShellArmor: @ 81FA0C6
	.string "Blocks critical hits.$"

gAbilityDescription_Cacophony: @ 81FA0DC
	.string "Avoids sound-based moves.$"

gAbilityDescription_AirLock: @ 81FA0F6
	.string "Negates weather effects.$"

	.align 2
gAbilityDescriptions:: @ 81FA110
	.int gAbilityDescription_None
	.int gAbilityDescription_Stench
	.int gAbilityDescription_Drizzle
	.int gAbilityDescription_SpeedBoost
	.int gAbilityDescription_BattleArmor
	.int gAbilityDescription_Sturdy
	.int gAbilityDescription_Damp
	.int gAbilityDescription_Limber
	.int gAbilityDescription_SandVeil
	.int gAbilityDescription_Static
	.int gAbilityDescription_VoltAbsorb
	.int gAbilityDescription_WaterAbsorb
	.int gAbilityDescription_Oblivious
	.int gAbilityDescription_CloudNine
	.int gAbilityDescription_CompoundEyes
	.int gAbilityDescription_Insomnia
	.int gAbilityDescription_ColorChange
	.int gAbilityDescription_Immunity
	.int gAbilityDescription_FlashFire
	.int gAbilityDescription_ShieldDust
	.int gAbilityDescription_OwnTempo
	.int gAbilityDescription_SuctionCups
	.int gAbilityDescription_Intimidate
	.int gAbilityDescription_ShadowTag
	.int gAbilityDescription_RoughSkin
	.int gAbilityDescription_WonderGuard
	.int gAbilityDescription_Levitate
	.int gAbilityDescription_EffectSpore
	.int gAbilityDescription_Synchronize
	.int gAbilityDescription_ClearBody
	.int gAbilityDescription_NaturalCure
	.int gAbilityDescription_LightningRod
	.int gAbilityDescription_SereneGrace
	.int gAbilityDescription_SwiftSwim
	.int gAbilityDescription_Chlorophyll
	.int gAbilityDescription_Illuminate
	.int gAbilityDescription_Trace
	.int gAbilityDescription_HugePower
	.int gAbilityDescription_PoisonPoint
	.int gAbilityDescription_InnerFocus
	.int gAbilityDescription_MagmaArmor
	.int gAbilityDescription_WaterVeil
	.int gAbilityDescription_MagnetPull
	.int gAbilityDescription_Soundproof
	.int gAbilityDescription_RainDish
	.int gAbilityDescription_SandStream
	.int gAbilityDescription_Pressure
	.int gAbilityDescription_ThickFat
	.int gAbilityDescription_EarlyBird
	.int gAbilityDescription_FlameBody
	.int gAbilityDescription_RunAway
	.int gAbilityDescription_KeenEye
	.int gAbilityDescription_HyperCutter
	.int gAbilityDescription_Pickup
	.int gAbilityDescription_Truant
	.int gAbilityDescription_Hustle
	.int gAbilityDescription_CuteCharm
	.int gAbilityDescription_Plus
	.int gAbilityDescription_Minus
	.int gAbilityDescription_Forecast
	.int gAbilityDescription_StickyHold
	.int gAbilityDescription_ShedSkin
	.int gAbilityDescription_Guts
	.int gAbilityDescription_MarvelScale
	.int gAbilityDescription_LiquidOoze
	.int gAbilityDescription_Overgrow
	.int gAbilityDescription_Blaze
	.int gAbilityDescription_Torrent
	.int gAbilityDescription_Swarm
	.int gAbilityDescription_RockHead
	.int gAbilityDescription_Drought
	.int gAbilityDescription_ArenaTrap
	.int gAbilityDescription_VitalSpirit
	.int gAbilityDescription_WhiteSmoke
	.int gAbilityDescription_PurePower
	.int gAbilityDescription_ShellArmor
	.int gAbilityDescription_Cacophony
	.int gAbilityDescription_AirLock
