ContestString_DescHighlyAppealing:
	.string "A highly appealing move.$"
ContestString_DescStartled1:
	.string "After this move, the user is\nmore easily startled.$"
ContestString_DescGreatLock:
	.string "Makes a great appeal, but\nallows no more to the end.$"
ContestString_DescRepeatable:
	.string "Can be repeatedly used\nwithout boring the JUDGE.$"
ContestString_DescStartled2:
	.string "Can avoid being startled\nby others once.$"
ContestString_DescStartled3:
	.string "Can avoid being startled\nby others.$"
ContestString_DescStartled4:
	.string "Can avoid being startled\nby others a little.$"
ContestString_DescStartled5:
	.string "After this move, the user is\nless likely to be startled.$"
ContestString_DescStartled6:
	.string "Slightly startles the\nPOKéMON in front.$"
ContestString_DescStartled7:
	.string "Slightly startles those\nthat have made appeals.$"
ContestString_DescStartled8:
	.string "Startles the POKéMON that\nappealed before the user.$"
ContestString_DescStartled9:
	.string "Startles all POKéMON that\nhave done their appeals.$"
ContestString_DescStartled10:
	.string "Badly startles the\nPOKéMON in front.$"
ContestString_DescStartled11:
	.string "Badly startles those that\nhave made appeals.$"
ContestString_DescStartled12:
	.string "Startles the POKéMON that\nappealed before the user.$"
ContestString_DescStartled13:
	.string "Startles all POKéMON that\nappealed before the user.$"
ContestString_DescAttentionShift:
	.string "Shifts the JUDGE's\nattention from others.$"
ContestString_DescStartled14:
	.string "Startles the POKéMON that\nhas the JUDGE's attention.$"
ContestString_DescJamOthersMissTurn:
	.string "Jams the others, and misses\none turn of appeals.$"
ContestString_DescStartled15:
	.string "Startles POKéMON that\nmade a same-type appeal.$"
ContestString_DescStartled16:
	.string "Badly startles POKéMON\nthat made COOL appeals.$"
ContestString_DescStartled17:
	.string "Badly startles POKéMON\nthat made BEAUTY appeals.$"
ContestString_DescStartled18:
	.string "Badly startles POKéMON\nthat made CUTE appeals.$"
ContestString_DescStartled19:
	.string "Badly startles POKéMON\nthat made SMART appeals.$"
ContestString_DescStartled20:
	.string "Badly startles POKéMON\nthat made TOUGH appeals.$"
ContestString_DescNervousOne:
	.string "Makes one POKéMON after\nthe user nervous.$"
ContestString_DescNervousAllAfter:
	.string "Makes all POKéMON after\nthe user nervous.$"
ContestString_DescConditionWorseBefore:
	.string "Worsens the condition of\nthose that made appeals.$"
ContestString_DescStartled21:
	.string "Badly startles POKéMON in\ngood condition.$"
ContestString_DescGreatWhenFirst:
	.string "The appeal works great if\nperformed first.$"
ContestString_DescGreatWhenLast:
	.string "The appeal works great if\nperformed last.$"
ContestString_DescAppealGoodBeforeAll:
	.string "Makes the appeal as good\nas those before it.$"
ContestString_DescAppealGoodBeforeOne:
	.string "Makes the appeal as good\nas the one before it.$"
ContestString_DescBetterWhenLater:
	.string "The appeal works better\nthe later it is performed.$"
ContestString_DescAffectedByTiming:
	.string "The appeal's quality varies\ndepending on its timing.$"
ContestString_DescBetterWhenSameType:
	.string "Works well if it's the same\ntype as the one before.$"
ContestString_DescBetterWhenDiffType:
	.string "Works well if different in\ntype than the one before.$"
ContestString_DescAffectedByFront:
	.string "Affected by how well the\nappeal in front goes.$"
ContestString_DescConditionUp:
	.string "Ups the user's condition.\nHelps prevent nervousness.$"
ContestString_DescAffectedByCondition:
	.string "The appeal works well if the\nuser's condition is good.$"
ContestString_DescAppealEarlier:
	.string "The next appeal can be made\nearlier next turn.$"
ContestString_DescAppealLater:
	.string "The next appeal can be made\nlater next turn.$"
ContestString_DescRandomOrderEasier:
	.string "Makes the next turn's order\nmore easily scrambled.$"
ContestString_DescRandomOrder:
	.string "Scrambles the order of\nappeals on the next turn.$"
ContestString_DescAnyExcitement:
	.string "An appeal that excites the\naudience in any CONTEST.$"
ContestString_DescStartled22:
	.string "Badly startles all POKéMON\nthat made good appeals.$"
ContestString_DescScaleWithExcitement:
	.string "The appeal works best the\nmore the crowd is excited.$"
ContestString_DescStopExcitement:
	.string "Temporarily stops the\ncrowd from growing excited.$"

	.align 2
gContestEffectStrings:: @ 83CADD4
	.int ContestString_DescHighlyAppealing
	.int ContestString_DescStartled1
	.int ContestString_DescGreatLock
	.int ContestString_DescRepeatable
	.int ContestString_DescStartled2
	.int ContestString_DescStartled3
	.int ContestString_DescStartled4
	.int ContestString_DescStartled5
	.int ContestString_DescStartled6
	.int ContestString_DescStartled7
	.int ContestString_DescStartled8
	.int ContestString_DescStartled9
	.int ContestString_DescStartled10
	.int ContestString_DescStartled11
	.int ContestString_DescStartled12
	.int ContestString_DescStartled13
	.int ContestString_DescAttentionShift
	.int ContestString_DescStartled14
	.int ContestString_DescJamOthersMissTurn
	.int ContestString_DescStartled15
	.int ContestString_DescStartled16
	.int ContestString_DescStartled17
	.int ContestString_DescStartled18
	.int ContestString_DescStartled19
	.int ContestString_DescStartled20
	.int ContestString_DescNervousOne
	.int ContestString_DescNervousAllAfter
	.int ContestString_DescConditionWorseBefore
	.int ContestString_DescStartled21
	.int ContestString_DescGreatWhenFirst
	.int ContestString_DescGreatWhenLast
	.int ContestString_DescAppealGoodBeforeAll
	.int ContestString_DescAppealGoodBeforeOne
	.int ContestString_DescBetterWhenLater
	.int ContestString_DescAffectedByTiming
	.int ContestString_DescBetterWhenSameType
	.int ContestString_DescBetterWhenDiffType
	.int ContestString_DescAffectedByFront
	.int ContestString_DescConditionUp
	.int ContestString_DescAffectedByCondition
	.int ContestString_DescAppealEarlier
	.int ContestString_DescAppealLater
	.int ContestString_DescRandomOrderEasier
	.int ContestString_DescRandomOrder
	.int ContestString_DescAnyExcitement
	.int ContestString_DescStartled22
	.int ContestString_DescScaleWithExcitement
	.int ContestString_DescStopExcitement

ContestString_MoveRainDance:
	.string "RAIN DANCE$"
ContestString_MoveRage:
	.string "RAGE$"
ContestString_MoveFocusEnergy:
	.string "FOCUS ENERGY$"
ContestString_MoveHypnosis:
	.string "HYPNOSIS$"
ContestString_MoveSoftboiled:
	.string "SOFTBOILED$"
ContestString_MoveHornAttack:
	.string "HORN ATTACK$"
ContestString_MoveSwordsDance:
	.string "SWORDS DANCE$"
ContestString_MoveConversion:
	.string "CONVERSION$"
ContestString_MoveSunnyDay:
	.string "SUNNY DAY$"
ContestString_MoveRest:
	.string "REST$"
ContestString_MoveVicegrip:
	.string "VICEGRIP$"
ContestString_MoveDefenseCurl:
	.string "DEFENSE CURL$"
ContestString_MoveLockOn:
	.string "LOCK-ON$"

	.align 2
	.int ContestString_MoveRainDance
	.int ContestString_MoveRainDance
	.int ContestString_MoveRage
	.int ContestString_MoveFocusEnergy
	.int ContestString_MoveHypnosis
	.int ContestString_MoveSoftboiled
	.int ContestString_MoveHornAttack
	.int ContestString_MoveSwordsDance
	.int ContestString_MoveConversion
	.int ContestString_MoveSunnyDay
	.int ContestString_MoveRest
	.int ContestString_MoveVicegrip
	.int ContestString_MoveDefenseCurl
	.int ContestString_MoveLockOn

ContestString_Cool:
	.string "COOL$"
ContestString_Beauty:
	.string "BEAUTY$"
ContestString_Cute:
	.string "CUTE$"
ContestString_Smart:
	.string "SMART$"
ContestString_Tough:
	.string "TOUGH$"

	.align 2
gContestCategoryNames:: @ 83CAF70
	.int ContestString_Cool
	.int ContestString_Beauty
	.int ContestString_Cute
	.int ContestString_Smart
	.int ContestString_Tough

gText_Contest_WhichMoveWillBePlayed:: @ 83CAF84
	.string "Appeal no. {NAME_END}!\nWhich move will be played?$"

gText_Contest_ButItCantParticipate:: @ 83CAFAE
	.string "Appeal no. {NAME_END}!\nBut it can't participate!$"

gUnknown_083CAFD7:: @ 83CAFD7
	.string "{STR_VAR_1} appealed with\n{STR_VAR_2}!$"
	.string "The other POKéMON\nmade moves.{PAUSE 60}$"

gUnknown_083CB00D:: @ 83CB00D
	.string "{STR_VAR_1} was watching\nthe others.{PAUSE 60}$"

gUnknown_083CB02C:: @ 83CB02C
	.string "We're all out of\nAppeal Time!{PAUSE 60}$"
	.string "{STR_VAR_1}'s {STR_VAR_3}\nmove {STR_VAR_2}!{PAUSE 60}$"
	.string "TRICK$"
	.string "SPECIAL$"
ContestString_AppealJammed:
	.string "But the appeal was\njammed.$"
ContestString_FollowLead:
	.string "It followed another\nPOKéMON's lead.$"
ContestString_MessedUp:
	.string "But it messed up.$"
ContestString_BetterUsual:
	.string "It went better than\nusual.$"
ContestString_JudgeLookAway:
	.string "The JUDGE looked away\nfor some reason.$"
ContestString_WorkHard:
	.string "It worked hard to build on\npast mistakes.$"
ContestString_NoMoreMoves:
	.string "It can't make any more\nmoves.$"
ContestString_WorkReallyWell:
	.string "It worked frighteningly\nwell.$"
ContestString_WorkHardStandout:
	.string "It worked as hard as the\nstandout POKéMON.$"
ContestString_JudgeExpectantly:
	.string "The JUDGE looked on\nexpectantly.$"
ContestString_WorkRatherWell:
	.string "It worked rather well.$"
ContestString_WorkBetter:
	.string "It worked a little better\nthan usual.$"

	.align 2
	.int ContestString_AppealJammed
	.int ContestString_FollowLead
	.int ContestString_MessedUp
	.int ContestString_BetterUsual
	.int ContestString_BetterUsual
	.int ContestString_JudgeLookAway
	.int ContestString_WorkHard
	.int ContestString_NoMoreMoves
	.int ContestString_WorkReallyWell
	.int ContestString_WorkHardStandout
	.int ContestString_JudgeExpectantly
	.int ContestString_WorkRatherWell
	.int ContestString_WorkBetter

ContestString_StandOutNone:
	.string "{STR_VAR_1} failed to\nstand out at all...{PAUSE_UNTIL_PRESS}$"
ContestString_StandOutNotMuch:
	.string "{STR_VAR_1} didn't stand\nout very much...{PAUSE_UNTIL_PRESS}$"
ContestString_StandOutLittle:
	.string "{STR_VAR_1} caught a\nlittle attention.{PAUSE_UNTIL_PRESS}$"
ContestString_StandOutLot:
	.string "{STR_VAR_1} attracted a\nlot of attention.{PAUSE_UNTIL_PRESS}$"
ContestString_StandOutTotal:
	.string "{STR_VAR_1} commanded\ntotal attention.{PAUSE_UNTIL_PRESS}$"
ContestString_StandOutDidnt:
	.string "{STR_VAR_1} hasn't made\nits appeal.{PAUSE_UNTIL_PRESS}$"

	.align 2
gContestStandOutStrings:: @ 83CB2F0
	.int ContestString_StandOutNone
	.int ContestString_StandOutNotMuch
	.int ContestString_StandOutLittle
	.int ContestString_StandOutLot
	.int ContestString_StandOutTotal
	.int ContestString_StandOutDidnt

ContestString_AppealAnticipation3:
	.string "Anticipation swelled for\n{STR_VAR_1}'s appeal next.$"
ContestString_JudgeSatisfied:
	.string "The JUDGE was very\nsatisfied.$"
ContestString_Terminator:
	.string "$"
ContestString_JudgeHeldFirm:
	.string "The JUDGE 's views on\n{STR_VAR_1} held firm.$"
ContestString_ChangedPerceptions:
	.string "{STR_VAR_1}'s {STR_VAR_3}\nchanged perceptions.$"
ContestString_AppealWoreOff:
	.string "{STR_VAR_1}'s appeal\neffect wore off.$"
ContestString_AppealWoreOff2:
	.string "The special appeal's\neffect wore off.$"
ContestString_AppealLookSame:
	.string "Everyone's appeals were\nmade to look the same.$"
ContestString_AppealCheapened:
	.string "{STR_VAR_2}'s appeal was\ncheapened.$"
ContestString_AppealCheapened2:
	.string "It cheapened the appeal\nof those ahead.$"
ContestString_AppealAttentionStolen:
	.string "It stole attention away\nfrom {STR_VAR_2}.$"
ContestString_AppealCheapened3:
	.string "It cheapened\n{STR_VAR_2}'s appeal.$"
ContestString_AppealCheapened4:
	.string "It severely cheapened\nother appeals.$"
ContestString_AppealAnticipation:
	.string "Anticipation swelled for\n{STR_VAR_1}'s appeal next.$"
ContestString_AppealCheapened5:
	.string "It cheapened the appeal\nof those ahead.$"
ContestString_AppealCheapened6:
	.string "It cheapened the JUDGE's\nfavorite appeal.$"
ContestString_AppealCheapened7:
	.string "The appeals of others\nwere cheapened by half.$"
ContestString_JammedStoodOut:
	.string "It stood out to make up\nfor being jammed.$"
ContestString_AppealNoMore:
	.string "It can't participate in\nappeals any more.$"
ContestString_AppealTouched:
	.string "It touched the JUDGE for\na fantastic appeal.$"
ContestString_AppealAnticipation2:
	.string "Anticipation rose for\nupcoming appeals.$"
ContestString_AppealStoodOut2:
	.string "It stood out as much as\nspecial appeals.$"
ContestString_AppealStoodOut3:
	.string "It stood out as much as\n{STR_VAR_1}.$"
ContestString_JammedAppealsNotice:
	.string "Jammed appeals were made\neven less noticeable.$"
ContestString_AppealSame:
	.string "Everyone's appeals were\nmade the same.$"
ContestString_AppealFullWorse:
	.string "Its {STR_VAR_1} is full.\nIt worsened its appeal.$"

	.align 2
	.int ContestString_JudgeHeldFirm
	.int ContestString_ChangedPerceptions
	.int ContestString_Terminator
	.int ContestString_AppealWoreOff
	.int ContestString_AppealWoreOff2
	.int ContestString_AppealLookSame
	.int ContestString_AppealCheapened
	.int ContestString_AppealCheapened2
	.int ContestString_AppealAttentionStolen
	.int ContestString_AppealCheapened3
	.int ContestString_AppealCheapened4
	.int ContestString_AppealAnticipation
	.int ContestString_AppealCheapened5
	.int ContestString_AppealCheapened6
	.int ContestString_AppealCheapened7
	.int ContestString_JammedStoodOut
	.int ContestString_AppealNoMore
	.int ContestString_AppealTouched
	.int ContestString_AppealAnticipation2
	.int ContestString_AppealStoodOut2
	.int ContestString_AppealStoodOut3
	.int ContestString_Terminator
	.int ContestString_Terminator
	.int ContestString_Terminator
	.int ContestString_JammedAppealsNotice
	.int ContestString_AppealSame
ContestString_MoreConscious:
	.string "It became more conscious\nof the other POKéMON.{PAUSE 60}$"
ContestString_NoAppeal:
	.string "{STR_VAR_1} can't make an\nappeal after this.{PAUSE 60}$"
ContestString_SettleDown:
	.string "It settled down just a\nlittle bit.{PAUSE 60}$"
ContestString_ObliviousToOthers:
	.string "It became oblivious to\nthe other POKéMON.{PAUSE 60}$"
ContestString_LessAware:
	.string "It became less aware of\nthe other POKéMON.{PAUSE 60}$"
ContestString_StoppedCaring:
	.string "It stopped caring about\nother POKéMON much.{PAUSE 60}$"
ContestString_StartleAttempt:
	.string "It tried to startle the\nother POKéMON.{PAUSE 60}$"
ContestString_DazzleAttempt:
	.string "It tried to dazzle the\nothers.{PAUSE 60}$"
ContestString_JudgeLookAway2:
	.string "The JUDGE looked away\nfrom {STR_VAR_1}.{PAUSE 60}$"
ContestString_UnnerveAttempt:
	.string "It tried to unnerve the\nnext POKéMON.{PAUSE 60}$"
ContestString_Nervous:
	.string "{STR_VAR_1} became\nnervous.{PAUSE 60}$"
ContestString_UnnerveWaiting:
	.string "The appeal tried to\nunnerve waiting POKéMON.{PAUSE 60}$"
ContestString_TauntWell:
	.string "It taunted POKéMON\ndoing well.{PAUSE 60}$"
ContestString_RegainedForm:
	.string "{STR_VAR_1} regained its\nform.{PAUSE 60}$"
ContestString_JamWell:
	.string "It tried to jam POKéMON\ndoing well.{PAUSE 60}$"
ContestString_HustleStandout:
	.string "The standout {STR_VAR_1}\nhustled even more.{PAUSE 60}$"
ContestString_WorkHardUnnoticed:
	.string "The largely unnoticed\n{STR_VAR_1} worked hard.{PAUSE 60}$"
ContestString_WorkBefore:
	.string "It worked as much as\nPOKéMON before it.{PAUSE 60}$"
ContestString_AppealNotWell:
	.string "{STR_VAR_1}'s appeal did\nnot go well.{PAUSE 60}$"
ContestString_WorkPreceding:
	.string "It worked as much as the\npreceding POKéMON.{PAUSE 60}$"
ContestString_AppealNotWell2:
	.string "{STR_VAR_1}'s appeal did\nnot go well.{PAUSE 60}$"
ContestString_AppealNotShownWell:
	.string "{STR_VAR_1}'s appeal\ncouldn't be shown well.{PAUSE 60}$"
ContestString_AppealSlightlyWell:
	.string "{STR_VAR_1}'s appeal\nwent slightly well.{PAUSE 60}$"
ContestString_AppealPrettyWell:
	.string "{STR_VAR_1}'s appeal\nwent pretty well.{PAUSE 60}$"
ContestString_AppealExcellently:
	.string "{STR_VAR_1}'s appeal\nwent excellently.{PAUSE 60}$"
ContestString_AppealDud:
	.string "{STR_VAR_1}'s appeal was\na dud.{PAUSE 60}$"
ContestString_AppealNotVeryWell:
	.string "{STR_VAR_1}'s appeal did\nnot work very well.{PAUSE 60}$"
ContestString_AppealSlightlyWell2:
	.string "{STR_VAR_1}'s appeal\nwent slightly well.{PAUSE 60}$"
ContestString_AppealPrettyWell2:
	.string "{STR_VAR_1}'s appeal\nwent pretty well.{PAUSE 60}$"
ContestString_AppealVeryWell:
	.string "{STR_VAR_1}'s appeal\nwent very well.{PAUSE 60}$"
ContestString_AppealExcellently2:
	.string "{STR_VAR_1}'s appeal\nwent excellently.{PAUSE 60}$"
ContestString_SameTypeGood:
	.string "It's the same type as the\nPOKéMON before - good!{PAUSE 60}$"
ContestString_DiffTypeGood:
	.string "It's not the same type as\nthe one before - good!{PAUSE 60}$"
ContestString_StoodOutAsMuch:
	.string "It stood out much more\nthan the POKéMON before.{PAUSE 60}$"
ContestString_NotAsWell:
	.string "It didn't do as well as the\nPOKéMON before.{PAUSE 60}$"
ContestString_ConditionRose:
	.string "{STR_VAR_1}'s condition\nrose above usual.{PAUSE 60}$"
ContestString_HotStatus:
	.string "{STR_VAR_1}'s hot status\nmade it a great appeal!{PAUSE 60}$"
ContestString_MoveUpLine:
	.string "It moved up in line for\nthe next appeal.{PAUSE 60}$"
ContestString_MoveBackLine:
	.string "It moved back in line once\nfor the next appeal.{PAUSE 60}$"
ContestString_ScrambleOrder:
	.string "It scrambled up the\norder for the next turn.{PAUSE 60}$"

gUnknown_083CBD52:: @ 83CBD52
ContestString_JudgeExpectantly2::
	.string "The JUDGE looked at\n{STR_VAR_1} expectantly.{PAUSE 60}$"

gUnknown_083CBD79:: @ 83CBD79
ContestString_WentOverWell::
	.string "The appeal combo went\nover well.{PAUSE 60}$"

gUnknown_083CBD9D:: @ 83CBD9D
ContestString_WentOverVeryWell::
	.string "The appeal combo went\nover very well.{PAUSE 60}$"

gUnknown_083CBDC6:: @ 83CBDC6
ContestString_AppealComboExcellently::
	.string "The appeal combo went\nover excellently.{PAUSE 60}$"
ContestString_AvertGaze:
	.string "{STR_VAR_1} managed to\navert its gaze.{PAUSE 60}$"
ContestString_AvoidSeeing:
	.string "{STR_VAR_1} managed to\navoid seeing it.{PAUSE 60}$"
ContestString_NotFazed:
	.string "{STR_VAR_1} isn't fazed\nby that sort of thing.{PAUSE 60}$"
ContestString_LittleDistracted:
	.string "{STR_VAR_1} became a\nlittle distracted.{PAUSE 60}$"
ContestString_AttemptStartle:
	.string "It tried to startle the\nother POKéMON.{PAUSE 60}$"
ContestString_LookedDown:
	.string "{STR_VAR_1} looked down\nout of distraction.{PAUSE 60}$"
ContestString_TurnedBack:
	.string "{STR_VAR_1} turned back\nout of distraction.{PAUSE 60}$"
ContestString_UtterCry:
	.string "{STR_VAR_1} couldn't help\nuttering a cry.{PAUSE 60}$"
ContestString_LeaptUp:
	.string "{STR_VAR_1} couldn't help\nleaping up.{PAUSE 60}$"
ContestString_TrippedOver:
	.string "{STR_VAR_1} tripped over\nout of distraction.{PAUSE 60}$"

gUnknown_083CBF60:: @ 83CBF60
ContestString_TooNervous:
	.string "{STR_VAR_1} was too\nnervous to move.{PAUSE 60}$"
ContestString_MessedUp2:
	.string "But it messed up.{PAUSE 60}$"
ContestString_FailedTargetNervous:
	.string "But it failed to make\nthe target nervous.{PAUSE 60}$"
ContestString_FailedAnyoneNervous:
	.string "But it failed to make\nanyone nervous.{PAUSE 60}$"
ContestString_Ignored:
	.string "But it was ignored...{PAUSE 60}$"
ContestString_NoConditionImprove:
	.string "But it couldn't improve\nits condition...{PAUSE 60}$"
ContestString_BadConditionWeakAppeal:
	.string "Its bad condition\nresulted in a weak appeal.{PAUSE 60}$"
ContestString_Unaffected:
	.string "{STR_VAR_1} was\nunaffected.{PAUSE 60}$"

gUnknown_083CC075:: @ 83CC075
ContestString_DissapointedRepeat::
	.string "{STR_VAR_1} disappointed\nby repeating an appeal.{PAUSE 60}$"

gUnknown_083CC0A0:: @ 83CC0A0
ContestString_WentOverGreat::
	.string "{STR_VAR_1}'s {STR_VAR_3}\nwent over great.{PAUSE 60}$"

gUnknown_083CC0BC:: @ 83CC0BC
ContestString_DidntGoWell::
	.string "{STR_VAR_1}'s {STR_VAR_3}\ndidn't go over well here...{PAUSE 60}$"

gUnknown_083CC0E3:: @ 83CC0E3
ContestString_GotCrowdGoing::
	.string "{STR_VAR_1}'s {STR_VAR_3}\ngot the crowd going.{PAUSE 60}$"

gUnknown_083CC103:: @ 83CC103
ContestString_CantAppealNextTurn::
	.string "{STR_VAR_1} can't appeal\nnext turn...{PAUSE 60}$"
ContestString_AttractedAttention::
	.string "It attracted the crowd's\nattention.{PAUSE 60}$"

gUnknown_083CC14A:: @ 83CC14A
ContestString_CrowdWatches::
	.string "The crowd continues to\nwatch {STR_VAR_3}.{PAUSE 60}$"

gUnknown_083CC16E:: @ 83CC16E
ContestString_Ignored2::
	.string "{STR_VAR_1}'s\n{STR_VAR_2} is ignored.{PAUSE 60}$"

	.align 2
gUnknown_083CC188:: @ 83CC188
	.int ContestString_MoreConscious
	.int ContestString_NoAppeal
	.int ContestString_SettleDown
	.int ContestString_ObliviousToOthers
	.int ContestString_LessAware
	.int ContestString_StoppedCaring
	.int ContestString_StartleAttempt
	.int ContestString_DazzleAttempt
	.int ContestString_JudgeLookAway2
	.int ContestString_UnnerveAttempt
	.int ContestString_Nervous
	.int ContestString_UnnerveWaiting
	.int ContestString_TauntWell
	.int ContestString_RegainedForm
	.int ContestString_JamWell
	.int ContestString_HustleStandout
	.int ContestString_WorkHardUnnoticed
	.int ContestString_WorkBefore
	.int ContestString_AppealNotWell
	.int ContestString_WorkPreceding
	.int ContestString_AppealNotWell2
	.int ContestString_AppealNotShownWell
	.int ContestString_AppealSlightlyWell
	.int ContestString_AppealPrettyWell
	.int ContestString_AppealExcellently
	.int ContestString_AppealDud
	.int ContestString_AppealNotVeryWell
	.int ContestString_AppealSlightlyWell2
	.int ContestString_AppealPrettyWell2
	.int ContestString_AppealVeryWell
	.int ContestString_AppealExcellently2
	.int ContestString_SameTypeGood
	.int ContestString_DiffTypeGood
	.int ContestString_StoodOutAsMuch
	.int ContestString_NotAsWell
	.int ContestString_ConditionRose
	.int ContestString_HotStatus
	.int ContestString_MoveUpLine
	.int ContestString_MoveBackLine
	.int ContestString_ScrambleOrder
	.int ContestString_JudgeExpectantly2 @ expectantly
	.int ContestString_WentOverWell
	.int ContestString_WentOverVeryWell
	.int ContestString_AppealComboExcellently
	.int ContestString_AvertGaze
	.int ContestString_AvoidSeeing
	.int ContestString_NotFazed
	.int ContestString_LittleDistracted
	.int ContestString_AttemptStartle
	.int ContestString_LookedDown
	.int ContestString_TurnedBack
	.int ContestString_UtterCry
	.int ContestString_LeaptUp
	.int ContestString_TrippedOver
	.int ContestString_MessedUp2
	.int ContestString_FailedTargetNervous
	.int ContestString_FailedAnyoneNervous
	.int ContestString_Ignored
	.int ContestString_NoConditionImprove
	.int ContestString_BadConditionWeakAppeal
	.int ContestString_Unaffected
	.int ContestString_AttractedAttention

gText_Contest_Shyness:: @ 83CC280
	.string "shyness$"

gText_Contest_Anxiety:: @ 83CC288
	.string "anxiety$"

gText_Contest_Laziness:: @ 83CC290
	.string "laziness$"

gText_Contest_Hesitancy:: @ 83CC299
	.string "hesitancy$"

gText_Contest_Fear:: @ 83CC2A3
	.string "fear$"

ContestString_Coolness:
	.string "coolness$"
ContestString_Beauty2:
	.string "beauty$"
ContestString_Cuteness:
	.string "cuteness$"
ContestString_Smartness:
	.string "smartness$"
ContestString_Toughness:
	.string "toughness$"

	.align 2
gContestCategoryStrings:: @ 83CC2D8
	.int ContestString_Coolness
	.int ContestString_Beauty2
	.int ContestString_Cuteness
	.int ContestString_Smartness
	.int ContestString_Toughness

gUnknown_083CC2EC:: @ 83CC2EC
	.string "TENSION:$"

ContestString_CoolMove:
	.string "COOL Move$"

ContestString_BeautyMove:
	.string "BEAUTY Move$"

ContestString_CuteMove:
	.string "CUTE Move$"

ContestString_SmartMove:
	.string "SMART Move$"

ContestString_ToughMove:
	.string "TOUGH Move$"

ContestString_UnknownMoveType:
	.string "???$"

	.align 2
gUnknown_083CC330:: @ 83CC330
	.int ContestString_CoolMove
	.int ContestString_BeautyMove
	.int ContestString_CuteMove
	.int ContestString_SmartMove
	.int ContestString_ToughMove
	.int ContestString_UnknownMoveType

@ unused?
ContestString_Rank:
	.string "RANK$"

	.string "{HIGHLIGHT TRANSPARENT}{COLOR MAGENTA} $"
