gGiftRibbonDescriptionPart1_2003RegionalTourney:
	.string "2003 REGIONAL TOURNEY$"

gGiftRibbonDescriptionPart2_Champion:
	.string "CHAMPION RIBBON$"

gGiftRibbonDescriptionPart1_2003NationalTourney:
	.string "2003 NATIONAL TOURNEY$"

gGiftRibbonDescriptionPart1_2003GlobalCup:
	.string "2003 GLOBAL CUP$"

gGiftRibbonDescriptionPart2_RunnerUp:
	.string "Runner-up RIBBON$"

gGiftRibbonDescriptionPart2_Semifinalist:
	.string "Semifinalist RIBBON$"

gGiftRibbonDescriptionPart1_2004RegionalTourney:
	.string "2004 REGIONAL TOURNEY$"

gGiftRibbonDescriptionPart1_2004NationalTourney:
	.string "2004 NATIONAL TOURNEY$"

gGiftRibbonDescriptionPart1_2004GlobalCup:
	.string "2004 GLOBAL CUP$"

gGiftRibbonDescriptionPart1_2005RegionalTourney:
	.string "2005 REGIONAL TOURNEY$"

gGiftRibbonDescriptionPart1_2005NationalTourney:
	.string "2005 NATIONAL TOURNEY$"

gGiftRibbonDescriptionPart1_2005GlobalCup:
	.string "2005 GLOBAL CUP$"

gGiftRibbonDescriptionPart1_PokemonBattleCup:
	.string "POKéMON BATTLE CUP$"

gGiftRibbonDescriptionPart2_Participation:
	.string "Participation RIBBON$"

gGiftRibbonDescriptionPart1_PokemonLeague:
	.string "POKéMON LEAGUE$"

gGiftRibbonDescriptionPart1_AdvanceCup:
	.string "ADVANCE CUP$"

gGiftRibbonDescriptionPart1_PokemonTournament:
	.string "POKéMON Tournament$"

gGiftRibbonDescriptionPart2_Participation2:
	.string "Participation RIBBON$"

gGiftRibbonDescriptionPart1_PokemonEvent:
	.string "POKéMON Event$"

gGiftRibbonDescriptionPart1_PokemonFestival:
	.string "POKéMON Festival$"

gGiftRibbonDescriptionPart1_DifficultyClearing:
	.string "Difficulty-clearing$"

gGiftRibbonDescriptionPart2_Commemorative:
	.string "Commemorative RIBBON$"

gGiftRibbonDescriptionPart1_ClearingAllDifficulties:
	.string "RIBBON awarded for$"

gGiftRibbonDescriptionPart2_ClearingAllDifficulties:
	.string "clearing all difficulties.$"

gGiftRibbonDescriptionPart1_100StraightWin:
	.string "100-straight Win$"

gGiftRibbonDescriptionPart1_DarknessTower:
	.string "DARKNESS TOWER Clear$"

gGiftRibbonDescriptionPart1_RedTower:
	.string "RED TOWER Clear$"

gGiftRibbonDescriptionPart1_BlackironTower:
	.string "BLACKIRON TOWER Clear$"

gGiftRibbonDescriptionPart1_FinalTower:
	.string "FINAL TOWER Clear$"

gGiftRibbonDescriptionPart1_LegendMaking:
	.string "Legend-making$"

gGiftRibbonDescriptionPart1_PokemonCenterTokyo:
	.string "POKéMON CENTER TOKYO$"

gGiftRibbonDescriptionPart1_PokemonCenterOsaka:
	.string "POKéMON CENTER OSAKA$"

gGiftRibbonDescriptionPart1_PokemonCenterNagoya:
	.string "POKéMON CENTER NAGOYA$"

gGiftRibbonDescriptionPart1_PokemonCenterNY:
	.string "POKéMON CENTER NY$"

gGiftRibbonDescriptionPart1_SummerHolidays:
	.string "Summer Holidays RIBBON$"

gGiftRibbonDescriptionPart2_EmptyString:
	.string "$"

gGiftRibbonDescriptionPart1_WinterHolidays:
	.string "Winter Holidays RIBBON$"

gGiftRibbonDescriptionPart1_SpringHolidays:
	.string "Spring Holidays RIBBON$"

gGiftRibbonDescriptionPart1_Evergreen:
	.string "Evergreen RIBBON$"

gGiftRibbonDescriptionPart1_SpecialHoliday:
	.string "Special Holiday RIBBON$"

gGiftRibbonDescriptionPart1_HardWorker:
	.string "Hard Worker RIBBON$"

gGiftRibbonDescriptionPart1_LotsOfFriends:
	.string "Lots of Friends RIBBON$"

gGiftRibbonDescriptionPart1_FullOfEnergy:
	.string "Full of Energy RIBBON$"

gGiftRibbonDescriptionPart1_LovedPokemon:
	.string "A commemorative RIBBON$"

gGiftRibbonDescriptionPart2_LovedPokemon:
	.string "for a loved POKéMON.$"

gGiftRibbonDescriptionPart1_LoveForPokemon:
	.string "RIBBON that shows$"

gGiftRibbonDescriptionPart2_LoveForPokemon:
	.string "love for POKéMON.$"

	.align 2
gGiftRibbonDescriptions:: @ 83E158C
	.int gGiftRibbonDescriptionPart1_2003RegionalTourney,   gGiftRibbonDescriptionPart2_Champion
	.int gGiftRibbonDescriptionPart1_2003NationalTourney,   gGiftRibbonDescriptionPart2_Champion
	.int gGiftRibbonDescriptionPart1_2003GlobalCup,         gGiftRibbonDescriptionPart2_Champion
	.int gGiftRibbonDescriptionPart1_2003RegionalTourney,   gGiftRibbonDescriptionPart2_RunnerUp
	.int gGiftRibbonDescriptionPart1_2003NationalTourney,   gGiftRibbonDescriptionPart2_RunnerUp
	.int gGiftRibbonDescriptionPart1_2003GlobalCup,         gGiftRibbonDescriptionPart2_RunnerUp
	.int gGiftRibbonDescriptionPart1_2003RegionalTourney,   gGiftRibbonDescriptionPart2_Semifinalist
	.int gGiftRibbonDescriptionPart1_2003NationalTourney,   gGiftRibbonDescriptionPart2_Semifinalist
	.int gGiftRibbonDescriptionPart1_2003GlobalCup,         gGiftRibbonDescriptionPart2_Semifinalist
	.int gGiftRibbonDescriptionPart1_2004RegionalTourney,   gGiftRibbonDescriptionPart2_Champion
	.int gGiftRibbonDescriptionPart1_2004NationalTourney,   gGiftRibbonDescriptionPart2_Champion
	.int gGiftRibbonDescriptionPart1_2004GlobalCup,         gGiftRibbonDescriptionPart2_Champion
	.int gGiftRibbonDescriptionPart1_2004RegionalTourney,   gGiftRibbonDescriptionPart2_RunnerUp
	.int gGiftRibbonDescriptionPart1_2004NationalTourney,   gGiftRibbonDescriptionPart2_RunnerUp
	.int gGiftRibbonDescriptionPart1_2004GlobalCup,         gGiftRibbonDescriptionPart2_RunnerUp
	.int gGiftRibbonDescriptionPart1_2004RegionalTourney,   gGiftRibbonDescriptionPart2_Semifinalist
	.int gGiftRibbonDescriptionPart1_2004NationalTourney,   gGiftRibbonDescriptionPart2_Semifinalist
	.int gGiftRibbonDescriptionPart1_2004GlobalCup,         gGiftRibbonDescriptionPart2_Semifinalist
	.int gGiftRibbonDescriptionPart1_2005RegionalTourney,   gGiftRibbonDescriptionPart2_Champion
	.int gGiftRibbonDescriptionPart1_2005NationalTourney,   gGiftRibbonDescriptionPart2_Champion
	.int gGiftRibbonDescriptionPart1_2005GlobalCup,         gGiftRibbonDescriptionPart2_Champion
	.int gGiftRibbonDescriptionPart1_2005RegionalTourney,   gGiftRibbonDescriptionPart2_RunnerUp
	.int gGiftRibbonDescriptionPart1_2005NationalTourney,   gGiftRibbonDescriptionPart2_RunnerUp
	.int gGiftRibbonDescriptionPart1_2005GlobalCup,         gGiftRibbonDescriptionPart2_RunnerUp
	.int gGiftRibbonDescriptionPart1_2005RegionalTourney,   gGiftRibbonDescriptionPart2_Semifinalist
	.int gGiftRibbonDescriptionPart1_2005NationalTourney,   gGiftRibbonDescriptionPart2_Semifinalist
	.int gGiftRibbonDescriptionPart1_2005GlobalCup,         gGiftRibbonDescriptionPart2_Semifinalist
	.int gGiftRibbonDescriptionPart1_PokemonBattleCup,      gGiftRibbonDescriptionPart2_Champion
	.int gGiftRibbonDescriptionPart1_PokemonBattleCup,      gGiftRibbonDescriptionPart2_RunnerUp
	.int gGiftRibbonDescriptionPart1_PokemonBattleCup,      gGiftRibbonDescriptionPart2_Semifinalist
	.int gGiftRibbonDescriptionPart1_PokemonBattleCup,      gGiftRibbonDescriptionPart2_Participation
	.int gGiftRibbonDescriptionPart1_PokemonLeague,         gGiftRibbonDescriptionPart2_Champion
	.int gGiftRibbonDescriptionPart1_PokemonLeague,         gGiftRibbonDescriptionPart2_RunnerUp
	.int gGiftRibbonDescriptionPart1_PokemonLeague,         gGiftRibbonDescriptionPart2_Semifinalist
	.int gGiftRibbonDescriptionPart1_PokemonLeague,         gGiftRibbonDescriptionPart2_Participation
	.int gGiftRibbonDescriptionPart1_AdvanceCup,            gGiftRibbonDescriptionPart2_Champion
	.int gGiftRibbonDescriptionPart1_AdvanceCup,            gGiftRibbonDescriptionPart2_RunnerUp
	.int gGiftRibbonDescriptionPart1_AdvanceCup,            gGiftRibbonDescriptionPart2_Semifinalist
	.int gGiftRibbonDescriptionPart1_AdvanceCup,            gGiftRibbonDescriptionPart2_Participation
	.int gGiftRibbonDescriptionPart1_PokemonTournament,     gGiftRibbonDescriptionPart2_Participation2
	.int gGiftRibbonDescriptionPart1_PokemonEvent,          gGiftRibbonDescriptionPart2_Participation2
	.int gGiftRibbonDescriptionPart1_PokemonFestival,       gGiftRibbonDescriptionPart2_Participation2
	.int gGiftRibbonDescriptionPart1_DifficultyClearing,    gGiftRibbonDescriptionPart2_Commemorative
	.int gGiftRibbonDescriptionPart1_ClearingAllDifficulties, gGiftRibbonDescriptionPart2_ClearingAllDifficulties
	.int gGiftRibbonDescriptionPart1_100StraightWin,        gGiftRibbonDescriptionPart2_Commemorative
	.int gGiftRibbonDescriptionPart1_DarknessTower,         gGiftRibbonDescriptionPart2_Commemorative
	.int gGiftRibbonDescriptionPart1_RedTower,              gGiftRibbonDescriptionPart2_Commemorative
	.int gGiftRibbonDescriptionPart1_BlackironTower,        gGiftRibbonDescriptionPart2_Commemorative
	.int gGiftRibbonDescriptionPart1_FinalTower,            gGiftRibbonDescriptionPart2_Commemorative
	.int gGiftRibbonDescriptionPart1_LegendMaking,          gGiftRibbonDescriptionPart2_Commemorative
	.int gGiftRibbonDescriptionPart1_PokemonCenterTokyo,    gGiftRibbonDescriptionPart2_Commemorative
	.int gGiftRibbonDescriptionPart1_PokemonCenterOsaka,    gGiftRibbonDescriptionPart2_Commemorative
	.int gGiftRibbonDescriptionPart1_PokemonCenterNagoya,   gGiftRibbonDescriptionPart2_Commemorative
	.int gGiftRibbonDescriptionPart1_PokemonCenterNY,       gGiftRibbonDescriptionPart2_Commemorative
	.int gGiftRibbonDescriptionPart1_SummerHolidays,        gGiftRibbonDescriptionPart2_EmptyString
	.int gGiftRibbonDescriptionPart1_WinterHolidays,        gGiftRibbonDescriptionPart2_EmptyString
	.int gGiftRibbonDescriptionPart1_SpringHolidays,        gGiftRibbonDescriptionPart2_EmptyString
	.int gGiftRibbonDescriptionPart1_Evergreen,             gGiftRibbonDescriptionPart2_EmptyString
	.int gGiftRibbonDescriptionPart1_SpecialHoliday,        gGiftRibbonDescriptionPart2_EmptyString
	.int gGiftRibbonDescriptionPart1_HardWorker,            gGiftRibbonDescriptionPart2_EmptyString
	.int gGiftRibbonDescriptionPart1_LotsOfFriends,         gGiftRibbonDescriptionPart2_EmptyString
	.int gGiftRibbonDescriptionPart1_FullOfEnergy,          gGiftRibbonDescriptionPart2_EmptyString
	.int gGiftRibbonDescriptionPart1_LovedPokemon,          gGiftRibbonDescriptionPart2_LovedPokemon
	.int gGiftRibbonDescriptionPart1_LoveForPokemon,        gGiftRibbonDescriptionPart2_LoveForPokemon
