	.align 2

gTileset_General:: @ 8286CF4
	.byte TRUE @ is compressed
	.byte FALSE @ is secondary tileset
	.short 0 @ padding
	.int gTilesetTiles_General
	.int gTilesetPalettes_General
	.int gMetatiles_General
	.int gMetatileAttributes_General
	.int TilesetCB_General

	.align 2

gTileset_Petalburg:: @ 8286D0C
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.short 0 @ padding
	.int gTilesetTiles_Petalburg
	.int gTilesetPalettes_Petalburg
	.int gMetatiles_Petalburg
	.int gMetatileAttributes_Petalburg
	.int TilesetCB_Petalburg

	.align 2

gTileset_Rustboro:: @ 8286D24
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.short 0 @ padding
	.int gTilesetTiles_Rustboro
	.int gTilesetPalettes_Rustboro
	.int gMetatiles_Rustboro
	.int gMetatileAttributes_Rustboro
	.int TilesetCB_Rustboro

	.align 2

gTileset_Dewford:: @ 8286D3C
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.short 0 @ padding
	.int gTilesetTiles_Dewford
	.int gTilesetPalettes_Dewford
	.int gMetatiles_Dewford
	.int gMetatileAttributes_Dewford
	.int TilesetCB_Dewford

	.align 2

gTileset_Slateport:: @ 8286D54
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.short 0 @ padding
	.int gTilesetTiles_Slateport
	.int gTilesetPalettes_Slateport
	.int gMetatiles_Slateport
	.int gMetatileAttributes_Slateport
	.int TilesetCB_Slateport

	.align 2

gTileset_Mauville:: @ 8286D6C
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.short 0 @ padding
	.int gTilesetTiles_Mauville
	.int gTilesetPalettes_Mauville
	.int gMetatiles_Mauville
	.int gMetatileAttributes_Mauville
	.int TilesetCB_Mauville

	.align 2

gTileset_Lavaridge:: @ 8286D84
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.short 0 @ padding
	.int gTilesetTiles_Lavaridge
	.int gTilesetPalettes_Lavaridge
	.int gMetatiles_Lavaridge
	.int gMetatileAttributes_Lavaridge
	.int TilesetCB_Lavaridge

	.align 2

gTileset_Fallarbor:: @ 8286D9C
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.short 0 @ padding
	.int gTilesetTiles_Fallarbor
	.int gTilesetPalettes_Fallarbor
	.int gMetatiles_Fallarbor
	.int gMetatileAttributes_Fallarbor
	.int TilesetCB_Fallarbor

	.align 2

gTileset_Fortree:: @ 8286DB4
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.short 0 @ padding
	.int gTilesetTiles_Fortree
	.int gTilesetPalettes_Fortree
	.int gMetatiles_Fortree
	.int gMetatileAttributes_Fortree
	.int TilesetCB_Fortree

	.align 2

gTileset_Lilycove:: @ 8286DCC
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.short 0 @ padding
	.int gTilesetTiles_Lilycove
	.int gTilesetPalettes_Lilycove
	.int gMetatiles_Lilycove
	.int gMetatileAttributes_Lilycove
	.int TilesetCB_Lilycove

	.align 2

gTileset_Mossdeep:: @ 8286DE4
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.short 0 @ padding
	.int gTilesetTiles_Mossdeep
	.int gTilesetPalettes_Mossdeep
	.int gMetatiles_Mossdeep
	.int gMetatileAttributes_Mossdeep
	.int TilesetCB_Mossdeep

	.align 2

gTileset_EverGrande:: @ 8286DFC
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.short 0 @ padding
	.int gTilesetTiles_EverGrande
	.int gTilesetPalettes_EverGrande
	.int gMetatiles_EverGrande
	.int gMetatileAttributes_EverGrande
	.int TilesetCB_EverGrande

	.align 2

gTileset_Pacifidlog:: @ 8286E14
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.short 0 @ padding
	.int gTilesetTiles_Pacifidlog
	.int gTilesetPalettes_Pacifidlog
	.int gMetatiles_Pacifidlog
	.int gMetatileAttributes_Pacifidlog
	.int TilesetCB_Pacifidlog

	.align 2

gTileset_Sootopolis:: @ 8286E2C
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.short 0 @ padding
	.int gTilesetTiles_Sootopolis
	.int gTilesetPalettes_Sootopolis
	.int gMetatiles_Sootopolis
	.int gMetatileAttributes_Sootopolis
	.int TilesetCB_Sootopolis

	.align 2

gTileset_Building:: @ 8286E44
	.byte TRUE @ is compressed
	.byte FALSE @ is secondary tileset
	.short 0 @ padding
	.int gTilesetTiles_Building
	.int gTilesetPalettes_Building
	.int gMetatiles_Building
	.int gMetatileAttributes_Building
	.int TilesetCB_Building

	.align 2

gTileset_Shop:: @ 8286E5C
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.short 0 @ padding
	.int gTilesetTiles_Shop
	.int gTilesetPalettes_Shop
	.int gMetatiles_Shop
	.int gMetatileAttributes_Shop
	.int NULL @ animation callback

	.align 2

gTileset_PokemonCenter:: @ 8286E74
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.short 0 @ padding
	.int gTilesetTiles_PokemonCenter
	.int gTilesetPalettes_PokemonCenter
	.int gMetatiles_PokemonCenter
	.int gMetatileAttributes_PokemonCenter
	.int NULL @ animation callback

	.align 2

gTileset_Cave:: @ 8286E8C
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.short 0 @ padding
	.int gTilesetTiles_Cave
	.int gTilesetPalettes_Cave
	.int gMetatiles_Cave
	.int gMetatileAttributes_Cave
	.int TilesetCB_Cave

	.align 2

gTileset_PokemonSchool:: @ 8286EA4
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.short 0 @ padding
	.int gTilesetTiles_PokemonSchool
	.int gTilesetPalettes_PokemonSchool
	.int gMetatiles_PokemonSchool
	.int gMetatileAttributes_PokemonSchool
	.int NULL @ animation callback

	.align 2

gTileset_PokemonFanClub:: @ 8286EBC
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.short 0 @ padding
	.int gTilesetTiles_PokemonFanClub
	.int gTilesetPalettes_PokemonFanClub
	.int gMetatiles_PokemonFanClub
	.int gMetatileAttributes_PokemonFanClub
	.int NULL @ animation callback

	.align 2

gTileset_Unused1:: @ 8286ED4
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.short 0 @ padding
	.int gTilesetTiles_Unused1
	.int gTilesetPalettes_Unused1
	.int gMetatiles_Unused1
	.int gMetatileAttributes_Unused1
	.int NULL @ animation callback

	.align 2

gTileset_MeteorFalls:: @ 8286EEC
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.short 0 @ padding
	.int gTilesetTiles_MeteorFalls
	.int gTilesetPalettes_MeteorFalls
	.int gMetatiles_MeteorFalls
	.int gMetatileAttributes_MeteorFalls
	.int NULL @ animation callback

	.align 2

gTileset_OceanicMuseum:: @ 8286F04
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.short 0 @ padding
	.int gTilesetTiles_OceanicMuseum
	.int gTilesetPalettes_OceanicMuseum
	.int gMetatiles_OceanicMuseum
	.int gMetatileAttributes_OceanicMuseum
	.int NULL @ animation callback

	.align 2

gTileset_CableClub:: @ 8286F1C
	.byte FALSE @ is compressed
	.byte TRUE @ is secondary tileset
	.short 0 @ padding
	.int gTilesetTiles_CableClub
	.int gTilesetPalettes_CableClub
	.int gMetatiles_CableClub
	.int gMetatileAttributes_CableClub
	.int NULL @ animation callback

	.align 2

gTileset_SeashoreHouse:: @ 8286F34
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.short 0 @ padding
	.int gTilesetTiles_SeashoreHouse
	.int gTilesetPalettes_SeashoreHouse
	.int gMetatiles_SeashoreHouse
	.int gMetatileAttributes_SeashoreHouse
	.int NULL @ animation callback

	.align 2

gTileset_PrettyPetalFlowerShop:: @ 8286F4C
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.short 0 @ padding
	.int gTilesetTiles_PrettyPetalFlowerShop
	.int gTilesetPalettes_PrettyPetalFlowerShop
	.int gMetatiles_PrettyPetalFlowerShop
	.int gMetatileAttributes_PrettyPetalFlowerShop
	.int NULL @ animation callback

	.align 2

gTileset_PokemonDayCare:: @ 8286F64
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.short 0 @ padding
	.int gTilesetTiles_PokemonDayCare
	.int gTilesetPalettes_PokemonDayCare
	.int gMetatiles_PokemonDayCare
	.int gMetatileAttributes_PokemonDayCare
	.int NULL @ animation callback

	.align 2

gTileset_Facility:: @ 8286F7C
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.short 0 @ padding
	.int gTilesetTiles_Facility
	.int gTilesetPalettes_Facility
	.int gMetatiles_Facility
	.int gMetatileAttributes_Facility
	.int NULL @ animation callback

	.align 2

gTileset_BikeShop:: @ 8286F94
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.short 0 @ padding
	.int gTilesetTiles_BikeShop
	.int gTilesetPalettes_BikeShop
	.int gMetatiles_BikeShop
	.int gMetatileAttributes_BikeShop
	.int TilesetCB_BikeShop

	.align 2

gTileset_RusturfTunnel:: @ 8286FAC
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.short 0 @ padding
	.int gTilesetTiles_RusturfTunnel
	.int gTilesetPalettes_RusturfTunnel
	.int gMetatiles_RusturfTunnel
	.int gMetatileAttributes_RusturfTunnel
	.int NULL @ animation callback

	.align 2

gTileset_SecretBaseBrownCave:: @ 8286FC4
	.byte FALSE @ is compressed
	.byte TRUE @ is secondary tileset
	.short 0 @ padding
	.int gTilesetTiles_SecretBaseBrownCave
	.int gTilesetPalettes_SecretBaseBrownCave
	.int gMetatiles_SecretBaseSecondary
	.int gMetatileAttributes_SecretBaseSecondary
	.int NULL @ animation callback

	.align 2

gTileset_SecretBaseTree:: @ 8286FDC
	.byte FALSE @ is compressed
	.byte TRUE @ is secondary tileset
	.short 0 @ padding
	.int gTilesetTiles_SecretBaseTree
	.int gTilesetPalettes_SecretBaseTree
	.int gMetatiles_SecretBaseSecondary
	.int gMetatileAttributes_SecretBaseSecondary
	.int NULL @ animation callback

	.align 2

gTileset_SecretBaseShrub:: @ 8286FF4
	.byte FALSE @ is compressed
	.byte TRUE @ is secondary tileset
	.short 0 @ padding
	.int gTilesetTiles_SecretBaseShrub
	.int gTilesetPalettes_SecretBaseShrub
	.int gMetatiles_SecretBaseSecondary
	.int gMetatileAttributes_SecretBaseSecondary
	.int NULL @ animation callback

	.align 2

gTileset_SecretBaseBlueCave:: @ 828700C
	.byte FALSE @ is compressed
	.byte TRUE @ is secondary tileset
	.short 0 @ padding
	.int gTilesetTiles_SecretBaseBlueCave
	.int gTilesetPalettes_SecretBaseBlueCave
	.int gMetatiles_SecretBaseSecondary
	.int gMetatileAttributes_SecretBaseSecondary
	.int NULL @ animation callback

	.align 2

gTileset_SecretBaseYellowCave:: @ 8287024
	.byte FALSE @ is compressed
	.byte TRUE @ is secondary tileset
	.short 0 @ padding
	.int gTilesetTiles_SecretBaseYellowCave
	.int gTilesetPalettes_SecretBaseYellowCave
	.int gMetatiles_SecretBaseSecondary
	.int gMetatileAttributes_SecretBaseSecondary
	.int NULL @ animation callback

	.align 2

gTileset_SecretBaseRedCave:: @ 828703C
	.byte FALSE @ is compressed
	.byte TRUE @ is secondary tileset
	.short 0 @ padding
	.int gTilesetTiles_SecretBaseRedCave
	.int gTilesetPalettes_SecretBaseRedCave
	.int gMetatiles_SecretBaseSecondary
	.int gMetatileAttributes_SecretBaseSecondary
	.int NULL @ animation callback

	.align 2

gTileset_InsideOfTruck:: @ 8287054
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.short 0 @ padding
	.int gTilesetTiles_InsideOfTruck
	.int gTilesetPalettes_InsideOfTruck
	.int gMetatiles_InsideOfTruck
	.int gMetatileAttributes_InsideOfTruck
	.int NULL @ animation callback

	.align 2

gTileset_Unused2:: @ 828706C
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.short 0 @ padding
	.int gTilesetTiles_Unused2
	.int gTilesetPalettes_Unused2
	.int gMetatiles_Unused2
	.int gMetatileAttributes_Unused2
	.int NULL @ animation callback

	.align 2

gTileset_Contest:: @ 8287084
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.short 0 @ padding
	.int gTilesetTiles_Contest
	.int gTilesetPalettes_Contest
	.int gMetatiles_Contest
	.int gMetatileAttributes_Contest
	.int NULL @ animation callback

	.align 2

gTileset_LilycoveMuseum:: @ 828709C
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.short 0 @ padding
	.int gTilesetTiles_LilycoveMuseum
	.int gTilesetPalettes_LilycoveMuseum
	.int gMetatiles_LilycoveMuseum
	.int gMetatileAttributes_LilycoveMuseum
	.int NULL @ animation callback

	.align 2

gTileset_BrendansMaysHouse:: @ 82870B4
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.short 0 @ padding
	.int gTilesetTiles_BrendansMaysHouse
	.int gTilesetPalettes_BrendansMaysHouse
	.int gMetatiles_BrendansMaysHouse
	.int gMetatileAttributes_BrendansMaysHouse
	.int NULL @ animation callback

	.align 2

gTileset_Lab:: @ 82870CC
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.short 0 @ padding
	.int gTilesetTiles_Lab
	.int gTilesetPalettes_Lab
	.int gMetatiles_Lab
	.int gMetatileAttributes_Lab
	.int NULL @ animation callback

	.align 2

gTileset_Underwater:: @ 82870E4
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.short 0 @ padding
	.int gTilesetTiles_Underwater
	.int gTilesetPalettes_Underwater
	.int gMetatiles_Underwater
	.int gMetatileAttributes_Underwater
	.int TilesetCB_Underwater

	.align 2

gTileset_PetalburgGym:: @ 82870FC
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.short 0 @ padding
	.int gTilesetTiles_PetalburgGym
	.int gTilesetPalettes_PetalburgGym
	.int gMetatiles_PetalburgGym
	.int gMetatileAttributes_PetalburgGym
	.int NULL @ animation callback

	.align 2

gTileset_SootopolisGym:: @ 8287114
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.short 0 @ padding
	.int gTilesetTiles_SootopolisGym
	.int gTilesetPalettes_SootopolisGym
	.int gMetatiles_SootopolisGym
	.int gMetatileAttributes_SootopolisGym
	.int TilesetCB_SootopolisGym

	.align 2

gTileset_GenericBuilding:: @ 828712C
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.short 0 @ padding
	.int gTilesetTiles_GenericBuilding
	.int gTilesetPalettes_GenericBuilding
	.int gMetatiles_GenericBuilding
	.int gMetatileAttributes_GenericBuilding
	.int NULL @ animation callback

	.align 2

gTileset_MauvilleGameCorner:: @ 8287144
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.short 0 @ padding
	.int gTilesetTiles_MauvilleGameCorner
	.int gTilesetPalettes_MauvilleGameCorner
	.int gMetatiles_MauvilleGameCorner
	.int gMetatileAttributes_MauvilleGameCorner
	.int NULL @ animation callback

	.align 2

gTileset_RustboroGym:: @ 828715C
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.short 0 @ padding
	.int gTilesetTiles_RustboroGym
	.int gTilesetPalettes_RustboroGym
	.int gMetatiles_RustboroGym
	.int gMetatileAttributes_RustboroGym
	.int NULL @ animation callback

	.align 2

gTileset_DewfordGym:: @ 8287174
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.short 0 @ padding
	.int gTilesetTiles_DewfordGym
	.int gTilesetPalettes_DewfordGym
	.int gMetatiles_DewfordGym
	.int gMetatileAttributes_DewfordGym
	.int NULL @ animation callback

	.align 2

gTileset_MauvilleGym:: @ 828718C
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.short 0 @ padding
	.int gTilesetTiles_MauvilleGym
	.int gTilesetPalettes_MauvilleGym
	.int gMetatiles_MauvilleGym
	.int gMetatileAttributes_MauvilleGym
	.int TilesetCB_MauvilleGym

	.align 2

gTileset_LavaridgeGym:: @ 82871A4
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.short 0 @ padding
	.int gTilesetTiles_LavaridgeGym
	.int gTilesetPalettes_LavaridgeGym
	.int gMetatiles_LavaridgeGym
	.int gMetatileAttributes_LavaridgeGym
	.int NULL @ animation callback

	.align 2

gTileset_TrickHousePuzzle:: @ 82871BC
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.short 0 @ padding
	.int gTilesetTiles_TrickHousePuzzle
	.int gTilesetPalettes_TrickHousePuzzle
	.int gMetatiles_TrickHousePuzzle
	.int gMetatileAttributes_TrickHousePuzzle
	.int NULL @ animation callback

	.align 2

gTileset_FortreeGym:: @ 82871D4
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.short 0 @ padding
	.int gTilesetTiles_FortreeGym
	.int gTilesetPalettes_FortreeGym
	.int gMetatiles_FortreeGym
	.int gMetatileAttributes_FortreeGym
	.int NULL @ animation callback

	.align 2

gTileset_MossdeepGym:: @ 82871EC
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.short 0 @ padding
	.int gTilesetTiles_MossdeepGym
	.int gTilesetPalettes_MossdeepGym
	.int gMetatiles_MossdeepGym
	.int gMetatileAttributes_MossdeepGym
	.int NULL @ animation callback

	.align 2

gTileset_Ship:: @ 8287204
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.short 0 @ padding
	.int gTilesetTiles_Ship
	.int gTilesetPalettes_Ship
	.int gMetatiles_Ship
	.int gMetatileAttributes_Ship
	.int NULL @ animation callback

	.align 2

gTileset_SecretBase:: @ 828721C
	.byte FALSE @ is compressed
	.byte FALSE @ is secondary tileset
	.short 0 @ padding
	.int gTilesetTiles_SecretBase
	.int gTilesetPalettes_SecretBase
	.int gMetatiles_SecretBasePrimary
	.int gMetatileAttributes_SecretBasePrimary
	.int NULL @ animation callback

	.align 2

gTileset_EliteFour:: @ 8287234
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.short 0 @ padding
	.int gTilesetTiles_EliteFour
	.int gTilesetPalettes_EliteFour
	.int gMetatiles_EliteFour
	.int gMetatileAttributes_EliteFour
	.int TilesetCB_EliteFour

	.align 2

gTileset_BattleTower:: @ 828724C
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.short 0 @ padding
	.int gTilesetTiles_BattleTower
	.int gTilesetPalettes_BattleTower
	.int gMetatiles_BattleTower
	.int gMetatileAttributes_BattleTower
	.int NULL @ animation callback
